:gift: add jbd interview
frenchgofr/frenchgofr pull request #11
Opened 2017-11-27 16:55 UTC by SiegfriedEhret

![](http://i.perezhilton.com/wp-content/uploads/2016/06/e3d8ddaa-4c88-4bd2-85e2-eb73f595c6d6.gif)

2017-11-27 17:52 UTC, alexjomin reviewed
![](https://media.giphy.com/media/8RxCFgu88jUbe/giphy.gif)

2017-11-27 17:52 UTC, alexjomin commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Bien, et j'étais très occupée ! Pendant que j'essayais de me préparer pendant la matinée, j'étais très anxieuse et mes slides n'étaient pas prêtes. J'avais 2 version de la présentation: une de 10 min
s/version/versions/

2017-11-27 17:52 UTC, alexjomin commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Dans Go 1.10 il y aura une interface utilisateur Web pour [pprof](https://golang.org/pkg/net/http/pprof/), ce qui permettra aux utilisateur d'avoir une vue sur pprof lorsque que le flag `-http` est a
s/contributionde/contribution de/

2017-11-27 17:52 UTC, alexjomin commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je pense que ce sont les fonctionnalités pour la concurrence, même si ce qui se passe en interne est parfois déroutant. Il y a des tonnes d'optimisations que j'ai découvertes quand je cherchais à en
s/passe/passer

2017-11-27 21:01 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Bien, et j'étais très occupée ! Pendant que j'essayais de me préparer pendant la matinée, j'étais très anxieuse et mes slides n'étaient pas prêtes. J'avais 2 version de la présentation: une de 10 min
deux versions

2017-11-27 21:02 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Bien, et j'étais très occupée ! Pendant que j'essayais de me préparer pendant la matinée, j'étais très anxieuse et mes slides n'étaient pas prêtes. J'avais 2 version de la présentation: une de 10 min
Pas de virgule ", et c'était"

2017-11-27 21:03 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Dans Go 1.10 il y aura une interface utilisateur Web pour [pprof](https://golang.org/pkg/net/http/pprof/), ce qui permettra aux utilisateur d'avoir une vue sur pprof lorsque que le flag `-http` est a
aux utilisateurs

2017-11-27 21:03 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Dans Go 1.10 il y aura une interface utilisateur Web pour [pprof](https://golang.org/pkg/net/http/pprof/), ce qui permettra aux utilisateur d'avoir une vue sur pprof lorsque que le flag `-http` est a
"lorsque que", que à supprimer.

2017-11-27 21:04 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Dans Go 1.10 il y aura une interface utilisateur Web pour [pprof](https://golang.org/pkg/net/http/pprof/), ce qui permettra aux utilisateur d'avoir une vue sur pprof lorsque que le flag `-http` est a
pas de virgule ", et ça fonctionnera"

2017-11-27 21:28 UTC, sebastienfr requested changes
![](https://media.giphy.com/media/12ZDIx1Mw1cXVm/giphy.gif)

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +En quelques sortes je dirige le projet et c'est un bon mélange de négociation avec d'autres personnes, d'écriture de code et un peu d'expérimentation. Aussi, écrire des documents de design, faire des
Aussi, écrire des documents de design, faire des revues... 
==> J'écris aussi des documents, je fais des revues de code, ...

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +En quelques sortes je dirige le projet et c'est un bon mélange de négociation avec d'autres personnes, d'écriture de code et un peu d'expérimentation. Aussi, écrire des documents de design, faire des
"cycles, et elles" pas de virgule.

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Dans Go 1.10 il y aura une interface utilisateur Web pour [pprof](https://golang.org/pkg/net/http/pprof/), ce qui permettra aux utilisateur d'avoir une vue sur pprof lorsque que le flag `-http` est a
https://twitter.com/rakyll/status/908748397305225217
On va ajouter le shortcode twitter pour ce tweet :

{{< tweet 908748397305225217 >}}

A tester

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +
A supprimer, ajouter le shortcode hugo à la place ;-)

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je pense que ce sont les fonctionnalités pour la concurrence, même si ce qui se passe en interne est parfois déroutant. Il y a des tonnes d'optimisations que j'ai découvertes quand je cherchais à en
article de rakyll sur le scheduler : https://rakyll.org/scheduler/

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je ne travaille pas directement sur le scheduler mais sur les outils de diagnostique, juste pour clarifier ! Mais parfois, je dois creuser pour comprendre le sens des choses et ce que nous avons beso
diagnostic

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je ne travaille pas directement sur le scheduler mais sur les outils de diagnostique, juste pour clarifier ! Mais parfois, je dois creuser pour comprendre le sens des choses et ce que nous avons beso
d'instrumentaliser => instrumenter

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je ne travaille pas directement sur le scheduler mais sur les outils de diagnostique, juste pour clarifier ! Mais parfois, je dois creuser pour comprendre le sens des choses et ce que nous avons beso
quand le projet Go est devenu un succès et que j'ai eu la possibliité j'ai rejoint le projet.
==>
que le projet Go est devenu un succès et que j'en ai eu la possibilité, je l'ai rejoint.
Attention coquille à possibilité aussi.

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je ne travaille pas directement sur le scheduler mais sur les outils de diagnostique, juste pour clarifier ! Mais parfois, je dois creuser pour comprendre le sens des choses et ce que nous avons beso
Je suis devenue passionnée => je me suis passionnée ou je suis devenue une passionnée

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Je ne travaille pas directement sur le scheduler mais sur les outils de diagnostique, juste pour clarifier ! Mais parfois, je dois creuser pour comprendre le sens des choses et ce que nous avons beso
diagnostics

2017-11-27 21:28 UTC, sebastienfr commented on blog/content/post/interview_jbd_dot_go_2017.md
> +Une fois que nous sommes d'accord sur le fait que Go peut être une bonne solution, la conversation évoluera vers «voici les choses que je souhaite faire» et «comment puis-je me former ?», alors la pe
J'ai réussi à apprendre Go si bien parce que j'ai eu de la chance.

Contribuer au projet d'un contributeur Go est génial aussi car (inverser aussi et génial)

2017-11-27 23:35 UTC, SiegfriedEhret commented
Merci pour les retours @alexjomin et @sebastienfr ! Je pense que je suis passé sur toutes vos remarques. Bisous !

2017-11-28 13:41 UTC, sebastienfr approved these changes

2017-11-28 13:41 UTC, merged