🚧 feat(dotGo): first start for dotGo summary
frenchgofr/frenchgofr pull request #16
Opened 2017-12-07 13:43 UTC by sebastienfr

J'ai attaqué la synthèse dotGo avec les présentation, etc...

![](https://media1.tenor.com/images/6c7f0a00931e6395798d350780981c02/tenor.gif?itemid=10430356)

2017-12-12 07:42 UTC, SiegfriedEhret requested changes

2017-12-12 07:42 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +On aperçois rapidement quelques speakers qui entrent se préparer. On discute avec quelques connaissances, collègues et amis et vous voilà aux portes du théâtre.
aperçois => aperçoit.

2017-12-12 07:42 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +On récupèrer son badge, dépose ses affaires au vestiaire et première étape incontournable : les goodies.
récupèrer => récupère

2017-12-12 07:42 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +# Arrivée
Le titre de l'article sera un `<h1>`. Il faut commencer par `##` plutôt.

2018-02-13 08:29 UTC, alexjomin commented on blog/content/post/dotgo2017.md
> +les erreurs dans vos programmes en Go. On termine sa présentation pour se rendre compte qu'il a réussi à nous instiller
👏 pour `instiller`

2018-02-13 08:36 UTC, alexjomin commented on blog/content/post/dotgo2017.md
> +Qui sait, avec l'avènement du machine learning, on n'écrira bientôt plus que les tests et les machines se chargeront du code !
faire une mention à sa boîte machinebox.io ?

2018-02-13 08:48 UTC, alexjomin commented on blog/content/post/dotgo2017.md
> +Sam Boyer est le core commiter de l'outil de gestion de dépendances de Go : **[dep](https://github.com/golang/dep)**.
s/commiter/committer

2018-02-13 08:48 UTC, alexjomin commented on blog/content/post/dotgo2017.md
> +Pari tenu pour cette édition 2017 de la dotGo. Un cadre inhabituel et agréable, un lineup de qualité ainsi qu'un savant équilibre entre talk et lighting
je rajouterai bien que cette année a senti un engouement plus fort de la part de la communauté francophone

2018-02-13 13:00 UTC, sebastienfr commented
A vos relecture, version finale selon moi.

2018-02-13 13:26 UTC, SiegfriedEhret approved these changes
C'est top ! Juste 2 micro trucs mais rien de méchant :)

2018-02-13 13:26 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +Cette année aussi nous sommes gâtés, tshirts homme et femme, stickers, tatouage et autres goodies des sponsors.
`t-shirts` non ?

2018-02-13 13:26 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +#### Sameer Ajmani : Simulating a real world system in go
Pourquoi pas `###` pour respecter la hiérarchie ?

2018-02-13 13:26 UTC, SiegfriedEhret commented on blog/content/post/dotgo2017.md
> +Le live coding le plus bluffant restera surement celui de Liz Rice. Avec un peu de préparation elle nous emmène
Ouais ! C'était top !

2018-02-13 20:36 UTC, merged