:gift: add interview deeeet
frenchgofr/frenchgofr pull request #24
Opened 2018-06-18 15:14 UTC by SiegfriedEhret

:warning: ne pas merger tout de suite, il faut attendre que ça sorte sur le site Sfeir...

![](https://s1.qwant.com/thumbr/0x0/8/8/bc2f9188a1bed25d047ecb5ff786c6f05a5b71999e611a7271a2d1d2aa3717/raw.jpg?u=https%3A%2F%2Fmedia.tenor.co%2Fimages%2F570bb459181c867209a3a53739cc55a3%2Fraw&q=0&b=1&p=0&a=1)

2018-07-23 13:52 UTC, sebastienfr requested changes

2018-07-23 13:52 UTC, sebastienfr commented on blog/content/post/interview_deeeet.md
> +Précédemment toutes les requêtes allaient directement sur l'API monolithique. Nous avons créer une passerelle d'API à mettre en amont. Toutes les requêtes arrivent sur celle-ci avant d'être redirigée
créé

2018-07-23 13:52 UTC, sebastienfr commented on blog/content/post/interview_deeeet.md
> +Précédemment toutes les requêtes allaient directement sur l'API monolithique. Nous avons créer une passerelle d'API à mettre en amont. Toutes les requêtes arrivent sur celle-ci avant d'être redirigée
lorsqu'il est prêt ==>

si nous souhaitons le migrer, nous allons créer le nouveau service et lorsqu'il sera prêt, changer la route dans la passerelle vers ce nouveau service.

2018-07-23 13:52 UTC, sebastienfr commented on blog/content/post/interview_deeeet.md
> +[Le livre dont deeet est un des auteurs:](https://www.amazon.co.jp/%E3%81%BF%E3%82%93%E3%81%AA%E3%81%AEGo%E8%A8%80%E8%AA%9E%E3%80%90%E7%8F%BE%E5%A0%B4%E3%81%A7%E4%BD%BF%E3%81%88%E3%82%8B%E5%AE%9F%E8%
URL courts ? https://www.amazon.co.jp/dp/477418392X

2018-07-23 13:52 UTC, sebastienfr commented on blog/content/post/interview_deeeet.md
> +Quand nous avons démarré les microservices, nous avons décidé que l'unité à déployer doit être un conteneur. Dans le monde des microservices, il est simple d'être polyglotte et nous souhaitons permet
doit être un conteneur ==>  devait être un conteneur

2018-07-23 14:49 UTC, SiegfriedEhret commented
@sebastienfr, :gift:

2018-07-23 16:53 UTC, rlespinasse approved these changes

2018-07-24 07:54 UTC, sebastienfr approved these changes

2018-07-24 07:54 UTC, merged