feat(interview): add interview emile vauge traefik
frenchgofr/frenchgofr pull request #32
Opened 2018-12-16 22:04 UTC by sebastienfr

closes #12

2018-12-17 00:33 UTC, SiegfriedEhret requested changes

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +title: "Interview Emile VAUGE Traefik"
Le titre n'est pas ouf. «Interview d'Emile Vauge, créateur de Traefik» ?

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +description: "La naissance et le futur de Traefik proxy par Emile VAUGE"
On peut mettre son nom avec juste la première lettre en majuscule ?

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Dans ton parcours tu as travaillé où ? Dans des startup, ESN, grandes entreprises ?
Cette ligne devrait être un titre.

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Dans ton parcours tu as travaillé où ? Dans des startup, ESN, grandes entreprises ?
Il manque un `s` à la fin de `startup`.

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Juste avant de lancer Traefik, j’étais chez Zenika où j’ai travaillé sur des sujets très divers et notamment dans le domaine de l'infrastructure.
Sur cette phrase on a 2 types d'apostrophes différent·es (je ne sais pas si c'est un ou une), à harmoniser sur l'ensemble.

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Cela nous à pris un certain  temps avant  d’arriver à une situation stable [rire].
`à pris` :arrow_right: `a pris`.

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Et je pense que c’est aussi une des raisons pour laquelle Traefik à beaucoup de succès,
`à beaucoup` :arrow_right: `a beaucoup`.

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +Alors il y a pas longtemps on a écrit un article sur notre blog, dans lequel on faisait du teasing de nos sujets de travail en cours.
Ajouter le lien vers l'article ?

2018-12-17 00:33 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +## Quel est ton regard sur la communauté des gophers en France ? Tu en côtoies pas mal, tu participes à de nombreux événements, quel est ton ressenti sur cette communauté et sur la façon dont Go est
@SiegfriedEhret tu as lu jusque là. :smile:

2018-12-17 23:00 UTC, sebastienfr commented
Merge pour publication.

2018-12-17 23:00 UTC, merged

2018-12-18 00:18 UTC, SiegfriedEhret reviewed
@sebastienfr j'ai retrouvé une petite pétouille. L'interview est top, bravo !

2018-12-18 00:18 UTC, SiegfriedEhret commented on blog/content/post/emile_vauge_traefik.md
> +L’équipe est vraiment super fier de ce que nous avons accompli.
`fier` :arrow_right: `fière`.