branche de travail de la dotGo
frenchgofr/frenchgofr pull request #7
Opened 2017-11-07 12:43 UTC by sebastienfr

branche de travail de la dotGo.
note perso et itw.

2017-11-08 21:21 UTC, SiegfriedEhret requested changes
@sebastienfr faut mettre la photo avec juste toi non ? ^^

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +c'est avoir une bibliothèque standard du langage qui soit plus petite.
Pourquoi le retour à la ligne ici ? (je pense qu'en html ça changera rien mais dans le doute...)

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
j'aimerai => j'aimerais ?

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Donc ce qui m'arrive des fois c'est que je fais des talks et au lieu de les faire une nième fois, j'en fait une vidéo et ça m'aide à passer à autre chose.
j'en fait => j'en fais

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +j'ai produit un épisode de [Justforfunc](https://www.youtube.com/watch?v=ySy3sR1LFCQ) sur le sujet.
Retour à la ligne inutile comme plus haut.

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +**Comme tu l'as annoncé tu vas chez [source{d}](https://blog.sourced.tech), est-ce que tu vas poursuivre ton travail pour la communauté Go ?**
Si tu mets le lien ici, pas besoin de le mettre en «N.D.L.R» plus haut.

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +donc je faisais beaucoup de choses qui n'étaient pas forcément liées au Go mais il fallait les faire.
Retour à la ligne inutile.

2017-11-08 21:21 UTC, SiegfriedEhret commented on blog/content/post/interview_francesc_dot_go_2017.md
> +le talk que j'ai donné aujourd'hui par exemple est plus dans l'esprit de ce que j'essaierai de faire dorénavant.
Retour à la ligne 😛

2017-11-08 21:28 UTC, sebastienfr commented
elle est floue, la mise au point s'est faite sur le fond de la salle et pas
nous :-(

Le 8 novembre 2017 à 22:21, Siegfried Ehret <notifications@github.com> a
écrit :

> *@SiegfriedEhret* requested changes on this pull request.
>
> @sebastienfr <https://github.com/sebastienfr> faut mettre la photo avec
> juste toi non ? ^^
> ------------------------------
>
> In blog/content/post/interview_francesc_dot_go_2017.md
> <https://github.com/frenchgofr/frenchgofr/pull/7#discussion_r149798391>:
>
> > +**Comment es-tu venu au Go ?**
> +
> +Ca c'est intéressant comme question. En fait je suis devenu "expert" C++ chez Amadeus à Sophia Antipolis et j'en ai fait pendant très très très longtemps.
> +Quand j'ai rejoint Google en tant que software engineer C++, j'en avais marre et je voulais faire quelque chose de nouveau.
> +J'ai eu l'opportunité de devenir developer relation et c'est quelque chose que j'ai beaucoup aimé.
> +A l'époque, mon sujet de master c'était un compilateur et je me suis dit que ça serait sympa de travailler en langage, ça serait un challenge intéressant.
> +Et comme le seul langage que Google avait c'était Go, donc j'ai commencé à l'apprendre.
> +Je parlais avec l'équipe Go et je leur disais que j'aimerai bien les rejoindre.
> +Après quelques interview avec plein de monde dont une avec [Rob Pike](https://fr.wikipedia.org/wiki/Rob_Pike) (un des créateur du langage N.D.L.R.), ils ont accepté ma candidature et j'ai pu rejoindre l'équipe Go.
> +Mon premier boulot dans l'équipe à été d'apprendre le Go et voir quels étaient les problèmes et essayer des les résoudre, ajouter de la documentation des tutoriaux et plein de choses comme ça.
> +
> +**La langage évolue, on [parle d'une version 2.0](https://www.youtube.com/watch?v=0Zbh_vmAKvk), quelles seraient tes envies pour une future version du langage ?**
> +
> +Donc forcément avec la version 2.0 du langage, la réponse que tout le monde attends c'est : les generics. Je trouve que les generics ça serait bien mais pas forcément le plus important pour moi.
> +Ce que j'aimerai bien voir maintenant qu'on a [dep](https://github.com/golang/dep), un outil qui nous permet d'avoir un meilleure gestion des bibliothèques autres que celles de la bibliothèque standard,
> +c'est avoir une bibliothèque standard du langage qui soit plus petite.
>
> Pourquoi le retour à la ligne ici ? (je pense qu'en html ça changera rien
> mais dans le doute...)
> ------------------------------
>
> In blog/content/post/interview_francesc_dot_go_2017.md
> <https://github.com/frenchgofr/frenchgofr/pull/7#discussion_r149798719>:
>
> > +Donc forcément avec la version 2.0 du langage, la réponse que tout le monde attends c'est : les generics. Je trouve que les generics ça serait bien mais pas forcément le plus important pour moi.
> +Ce que j'aimerai bien voir maintenant qu'on a [dep](https://github.com/golang/dep), un outil qui nous permet d'avoir un meilleure gestion des bibliothèques autres que celles de la bibliothèque standard,
> +c'est avoir une bibliothèque standard du langage qui soit plus petite.
> +Il y a beaucoup de choses dans la bibliothèque standard qui ne devraient pas être là, comme par exemple l'encodeur PNG ou JPG.
> +On en a pas vraiment besoin, c'est bien qu'elles soient là, mais s'il y a d'autres personnes qui peuvent faire mieux et plus rapide, pourquoi on ne leur laissera pas faire ?
> +On donne actuellement un avantage aux API de la bibliothèque standard, ce qui n'est pas forcément pertinent et comme [contribuer au langage](https://www.youtube.com/watch?v=DjZMKKfNVMc) lui même c'est plus difficile,
> +ça implique une évolution plus lente de ces bibliothèques.
> +J'aimerai bien corriger ce point mais on verra ce que l'avenir nous réserve.
> +
> +**Tu le disais précédemment, on te connais aussi pour [JustForFunc](http://youtube.com/c/justforfunc), est-ce que tu es beaucoup sollicité pour tes épisodes par les gophers ?**
> +
> +Oui, j'ai un [formulaire](http://form.justforfunc.com) et je reçois beaucoup d'idées. Je fais surtout des codes reviews et les gens aiment bien ça, ils veulent que je fasse la revue de leur code.
> +Je dois avouer que c'est pas toujours faisable parce qu'ils envoient parfois des vrais paquet de plusieurs dizaines de milliers de lignes de code.
> +Mais il m'est arrivé par exemple que parmi quelque chose d'assez grand, il y avait une partie ou un package intéressant et du coup je fais la revue d'un seul paquet et c'était très intéressant.
> +J'ai eu la chance de travailler chez Google et particulièrement dans l'équipe Go et ça m'a permis d'avoir des revues de code qui étaient vraiment très enrichissantes.
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
>
> j'aimerai => j'aimerais ?
> ------------------------------
>
> In blog/content/post/interview_francesc_dot_go_2017.md
> <https://github.com/frenchgofr/frenchgofr/pull/7#discussion_r149799006>:
>
> > +Oui, j'ai un [formulaire](http://form.justforfunc.com) et je reçois beaucoup d'idées. Je fais surtout des codes reviews et les gens aiment bien ça, ils veulent que je fasse la revue de leur code.
> +Je dois avouer que c'est pas toujours faisable parce qu'ils envoient parfois des vrais paquet de plusieurs dizaines de milliers de lignes de code.
> +Mais il m'est arrivé par exemple que parmi quelque chose d'assez grand, il y avait une partie ou un package intéressant et du coup je fais la revue d'un seul paquet et c'était très intéressant.
> +J'ai eu la chance de travailler chez Google et particulièrement dans l'équipe Go et ça m'a permis d'avoir des revues de code qui étaient vraiment très enrichissantes.
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
> +La façon la plus simple que j'ai trouvé de faire ça, c'est les vidéos. J'ai essayé d'écrire des articles de blog pour des revues de code et... ça marche pas (rires).
> +C'est beaucoup plus simple dans une vidéo de montrer comment tu changes le code.
> +
> +**Quel est le niveau de préparation pour tes épisodes ? Préparés au millimètre, un peu d'improvisation quand même ?**
> +
> +Il y a carrément de l'improvisation, il y a beaucoup de gens qui disent que c'est très bien que j'essaye de mettre des erreurs, je les mets pas, je les fais (rires).
> +Je fais des erreurs pendant que je code, c'est normal, tout le monde en fait, mais je ne les enlève pas et c'est ça aussi que les gens aiment bien.
> +Ca permet de montrer comment je fais quand quelque chose ne marche pas, quelle est ma façon de corriger les problèmes.
> +Sinon ça dépend beaucoup des épisodes. Il y a des épisodes qui m'ont demandés beaucoup de temps, par exemple un des épisodes le plus vus est celui sur le package [context](https://www.youtube.com/channel/UC_BzFbxG2za3bp5NRRRXJSw/videos), celui-là m'a pris plusieurs mois.
> +Mais parce qu'à la base c'était un talk que j'ai fait quatre fois et après j'en ai fait un épisode.
> +Donc ce qui m'arrive des fois c'est que je fais des talks et au lieu de les faire une nième fois, j'en fait une vidéo et ça m'aide à passer à autre chose.
>
> j'en fait => j'en fais
> ------------------------------
>
> In blog/content/post/interview_francesc_dot_go_2017.md
> <https://github.com/frenchgofr/frenchgofr/pull/7#discussion_r149799135>:
>
> > +J'ai eu la chance de travailler chez Google et particulièrement dans l'équipe Go et ça m'a permis d'avoir des revues de code qui étaient vraiment très enrichissantes.
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
> +La façon la plus simple que j'ai trouvé de faire ça, c'est les vidéos. J'ai essayé d'écrire des articles de blog pour des revues de code et... ça marche pas (rires).
> +C'est beaucoup plus simple dans une vidéo de montrer comment tu changes le code.
> +
> +**Quel est le niveau de préparation pour tes épisodes ?  [...]

2017-11-08 21:31 UTC, rlespinasse commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Je vais maintenant faire du Machine Learning sur du code source, l'idée c'est de faire du Big Data mais avec du code source comme données d'entrée (chez [source{d}](https://blog.sourced.tech) N.D.L.R
`N.D.L.R.` devrait être avant la note, non?

2017-11-08 21:31 UTC, rlespinasse commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Sinon je fais aussi des vidéos Youtube, ma chaîne s'appelle [JustForFunc](http://youtube.com/c/justforfunc) et apparamment il y a beaucoup de gens qui regarde ça, c'est génial (toute la dotGo à levé
`N.D.L.R.` devrait être avant la note, non?

2017-11-08 21:31 UTC, rlespinasse commented on blog/content/post/interview_francesc_dot_go_2017.md
> +J'ai eu l'opportunité de devenir developer relation et c'est quelque chose que j'ai beaucoup aimé.
**D**eveloper **R**elation comme au dessus

2017-11-08 21:31 UTC, rlespinasse commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Après quelques interview avec plein de monde dont une avec [Rob Pike](https://fr.wikipedia.org/wiki/Rob_Pike) (un des créateur du langage N.D.L.R.), ils ont accepté ma candidature et j'ai pu rejoindr
`N.D.L.R.` devrait être avant la note, non?

2017-11-09 14:52 UTC, sebastienfr commented on blog/content/post/interview_francesc_dot_go_2017.md
> +c'est avoir une bibliothèque standard du langage qui soit plus petite.
c'est juste en MD ca change rien et ça permet d'avoir des lignes pas trop longue dans l'IDE ou la console :-)

2017-11-09 14:53 UTC, sebastienfr commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
yep

2017-11-13 12:55 UTC, bnjjj requested changes

2017-11-13 12:55 UTC, bnjjj commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Mon premier boulot dans l'équipe à été d'apprendre le Go et voir quels étaient les problèmes et essayer des les résoudre, ajouter de la documentation des tutoriaux et plein de choses comme ça.
j'aurai mis le "et" à la dernière énumération, comme ça:
`Mon premier boulot dans l'équipe à été d'apprendre le Go et voir quels étaient les problèmes, essayer des les résoudre, ajouter de la documentation avec des tutoriaux et plein de choses comme ça.`

2017-11-13 12:55 UTC, bnjjj commented on blog/content/post/interview_francesc_dot_go_2017.md
> +**Tu le disais précédemment, on te connais aussi pour [JustForFunc](http://youtube.com/c/justforfunc), est-ce que tu es beaucoup sollicité pour tes épisodes par les gophers ?**
on te connait

2017-11-13 23:10 UTC, sebastienfr commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
futur première personne du singulier pas de "s"

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Ils font beaucoup de Go et d'[Open Source](https://github.com/src-d), je les rejoins en tant que VP Developer Relation.
"VP of Developer Relations"

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Sinon je fais aussi des vidéos Youtube, ma chaîne s'appelle [JustForFunc](http://youtube.com/c/justforfunc) et apparamment il y a beaucoup de gens qui regarde ça, c'est génial (toute la dotGo à levé
s/regarde/regardent/

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Ca c'est intéressant comme question. En fait je suis devenu "expert" C++ chez Amadeus à Sophia Antipolis et j'en ai fait pendant très très très longtemps.
Ça

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +J'ai eu l'opportunité de devenir Developer Relation et c'est quelque chose que j'ai beaucoup aimé.
Developer Relations

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Mon premier boulot dans l'équipe à été d'apprendre le Go et voir quels étaient les problèmes. J'ai essayé des les résoudre, ajouté de la documentation, des tutoriaux et plein de choses comme ça.
"de les résoudre"

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +On en a pas vraiment besoin, c'est bien qu'elles soient là, mais s'il y a d'autres personnes qui peuvent faire mieux et plus rapide, pourquoi on ne leur laissera pas faire ?
s/laissera/laisserait/

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +J'aimerai bien corriger ce point mais on verra ce que l'avenir nous réserve.
J'aimerais (c'est du conditionel)

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Elles me venaient de gens comme Rob Pike et j'aimerai pouvoir renvoyer l'ascenseur à la communauté et partager cette expérience.
C'est du conditionel en fait, donc du coup avec un s à la fin

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Sinon ça dépend beaucoup des épisodes. Il y a des épisodes qui m'ont demandés beaucoup de temps, par exemple un des épisodes le plus vus est celui sur le package [context](https://www.youtube.com/cha
le lien devrait être https://www.youtube.com/watch?v=LSzR0VEraWw

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Oui tout à fait ! Je vais même essayer de faire plus, car jusqu'à présent j'étais dans l'équipe Go mais j'étais aussi dans l'équipe [Google Cloud Plateforme](https://cloud.google.com),
Google Cloud Platform

2017-11-15 23:03 UTC, campoy commented on blog/content/post/interview_francesc_dot_go_2017.md
> +Tout le backend applicatif est écrit en Go, donc mon idée c'est de continuer à apprendre le Go forcément, mais aussi d'avoir des ingénieurs qui travaillent sur le backend pour faire plus de talk.
plus de talks

2017-11-16 09:07 UTC, merged